const fs = require('fs-extra')
const path = require('path')

const dist = path.resolve(__dirname, '../dist')
const distFonts = path.join(dist, 'fonts')
const distComponent = path.join(dist, 'component')
const distServer = path.join(dist, 'server')
const distHtml = path.join(dist, 'html')
const distHeader = path.join(distComponent, 'header')
const distSuites = path.join(distComponent, 'suites')

fs.removeSync(dist)
fs.mkdirpSync(distFonts)
fs.mkdirpSync(distComponent)
fs.mkdirpSync(distServer)
fs.mkdirpSync(distHtml)
fs.mkdirpSync(distHeader)
fs.mkdirpSync(distSuites)

require('./babel')
require('./postcss')
